---
title: "BMI_13_Companion"
author: "K Schaumberg"
date: '2022-05-20'
output: html_document
---
```{r}
library(haven)
library(readxl)
library(scorekeeper)
library(zscorer)
library(dplyr)

ALSPAC_Raw <- read_spss('ALSPAC.Raw.sav')%>% 
  filter(qlet == 'A')
```


```{r}
bmi_13_scoresheet <- read_excel('scoresheets/BMI/BMI_13_scoresheet.xlsx')
bmi_13 <- scorekeep(ALSPAC_Raw, bmi_13_scoresheet)
bmi_13 <- bmi_13[[4]]
```

```{r}
bmi_13$age_days_pr.13 = 157*30.4167
bmi_13$age_days_clinic.13 = 166*30.4167
bmi_13$sex_z = bmi_13$sex + 1
```

```{r}

bmi_13 <- addWGSR(bmi_13, sex = 'sex_z', firstPart = 'weight_pr.13', secondPart = 'height_pr.13', thirdPart = 'age_days_pr.13', index ='bfa', output = 'bmi_z_pr_2006.13', digits = 4)

bmi_13 <- addWGSR(bmi_13, sex = 'sex_z', firstPart = 'weight_clinic.13', secondPart = 'height_clinic.13', thirdPart = 'age_days_clinic.13', index ='bfa', output = 'bmi_z_clinic_2006.13', digits = 4)
```

```{r}
bmi_13 <- bmi_13 %>% 
  mutate (bmi_z_bestavail.13 = if_else (is.na(bmi_z_clinic_2006.13) == TRUE, bmi_z_pr_2006.13, bmi_z_clinic_2006.13)) %>% 
  select(!c('sex', 'sex_z', 'age_days_clinic.13', 'age_days_pr.13')) 

labelled::var_label(bmi_13$bmi_z_bestavail.13) <- 'BMI z-score based on clinic BMI if present, else parent-report BMI at age 13 using zscorer package (WHO 2006 zbmi-scores)'
labelled::var_label(bmi_13$bmi_z_clinic_2006.13)  <- 'BMI z-score based on clinic BMI, using WHO 2006 BMI z-scoring'
labelled::var_label(bmi_13$bmi_z_pr_2006.13)  <- 'BMI z-score based on self/parent-report BMI, using WHO 2006 BMI z-scoring'

```

```{r}
bmi_12_scoresheet <- read_excel('scoresheets/BMI/BMI_12_scoresheet.xlsx')
bmi_12 <- scorekeep(ALSPAC_Raw, bmi_12_scoresheet)
bmi_12 <- bmi_12[[3]]
bmi_12$age_days_clinic.12 = 154*30.4167
bmi_12 <- addWGSR(bmi_12, sex = 'sex', firstPart = 'weight_clinic.12', secondPart = 'height_clinic.12', thirdPart = 'age_days_clinic.12', index ='bfa', output = 'bmi_z_clinic_2006.12', digits = 4)
labelled::var_label(bmi_12$bmi_z_clinic_2006.12)  <- 'BMI z-score based on clinic BMI, using WHO 2006 BMI z-scoring - age 12'
bmi_12 <- bmi_12 %>%  
  select(!c('sex', 'age_days_clinic.12')) 
```

```{r}
bmi <- full_join(bmi_12, bmi_13)
```

```{r}
bmi_14_scoresheet <- read_excel('scoresheets/BMI/BMI_14_scoresheet.xlsx')
bmi_14 <- scorekeep(ALSPAC_Raw, bmi_14_scoresheet)
bmi_14 <- bmi_14[[3]]
bmi_14$age_days_pr.14 = 175*30.4167
bmi_14 <- addWGSR(bmi_14, sex = 'sex', firstPart = 'weight_pr.14', secondPart = 'height_pr.14', thirdPart = 'age_days_pr.14', index ='bfa', output = 'bmi_z_pr_2006_14', digits = 4)

labelled::var_label(bmi_14$bmi_z_pr_2006_14)  <- 'BMI z-score based on self/parent-report (puberty Q) BMI, using WHO 2006 BMI z-scoring - age 14'
bmi_14 <- bmi_14 %>%  
  select(!c('sex', 'age_days_pr.14')) 
```

```{r}
bmi <- full_join(bmi, bmi_14)

```


```{r}
cgwtools::resave(bmi, file = 'ALSPAC_Cleaned.RData')

```

