This is the Scoring Script for ALSPAC Data

# 0. Load packages
```{r, message=FALSE}
library(readxl)
library(haven)
library(cgwtools)
library(scorekeeper)
library(purrr)
library(tibble)
library(dplyr)
library(lubridate)
library(anytime)
library(tidyr)
library(Hmisc)
library(stringr)
library(zscorer)
library(expss)
```

## Load Data
```{r}
# Load Raw data; name cleaned data file for output
data <- read_sav('data/Schaumberg_22June22.sav') |> 
  filter(qlet == 'A')
```


## Clean known data issues

# 2. Scorekeep 

```{r, warning=FALSE}

# Load Individual Scoresheets
filenames <- list.files('scoresheets/clean/') # MAKE SURE THIS IS THE CORRECT DIRECTORY NAME
filenames <- paste('scoresheets/clean', filenames, sep = '/' )
ldf <- lapply(filenames, read_xlsx)

# List of Measure Names from the Scoresheets
measures <- list.files('scoresheets/clean') 
measures <- gsub('.xlsx*', '', measures)

# Names the scoresheets
names(ldf) <- measures

# Cleans and saves cleaned data for each measure 

x <- vector(mode = 'list', length = (length(measures)))
names(x) <- measures

tibble_func_1 <- function(x) {
  y = as_tibble(x)
  return (y) }

cleaned_data <- purrr::map(x, tibble_func_1)

for (i in 1:length(measures)) {
cleaned <- scorekeep(data, ldf[[i]])
cleaned_last <- cleaned[[max(ldf[[i]]$step)]]
cleaned_data[[i]] <-cleaned_last
}
```

## Run to get WHO BMI Z-scores for each Age 

```{r}

# adds in BMI and weights for a few that were missing from the orginal data; makes 'sex_z' variable with sex defined as 1 = Male 2 = Female for use in zscorer package 

cleaned_data$BMI <- cleaned_data$BMI |> 
  mutate(weight_clinic.186= bmi_clinic.186*(height_clinic.186/100)^2) |> 
  mutate(sex_z= sex+1) |> 
  pivot_longer(cols = matches("\\."), #pivots to long form
               names_sep = "\\.",
               names_to = c(".value", "assess_agemos")) |> 
  #Change out of range BMI values to NA (BMI > 50 or BMI < 8)
  mutate(bmi_pub = na_if(bmi_pub, gt(50)|lt(8))) |> 
  mutate(bmi_clinic = na_if(bmi_clinic, gt(50)|lt(8))) |> 
  mutate(bmi_bestavail  = na_if(bmi_bestavail, gt(50)|lt(8)))

cleaned_data$BMI <- cleaned_data$BMI |> 
  mutate(agedays_clinic = case_when(!is.na(agewks_clinc) ~ agewks_clinc*7,
                              !is.na(agemos_clinic) ~ agemos_clinic*30.437)) |> 
  mutate(agedays_pub = case_when(!is.na(agewks_pub) ~ agewks_pub*7,
                              !is.na(agemos_pub) ~ agemos_pub*30.437)) |> 
  mutate(agedays_bestavail = agemos_bestavail*30.437)

## adds in bmi z scores 
cleaned_data$BMI <- 
  zscorer::addWGSR(cleaned_data$BMI, sex = 'sex_z', firstPart = 'weight_pub', secondPart = 'height_pub', thirdPart = 'agedays_pub', index ='bfa', output = 'bmiz_pub', digits = 3)

cleaned_data$BMI <-
  zscorer::addWGSR(cleaned_data$BMI, sex = 'sex_z', firstPart = 'weight_clinic', secondPart = 'height_clinic', thirdPart = 'agedays_clinic', index ='bfa', output = 'bmiz_clinic', digits = 3)

cleaned_data$BMI <-
  zscorer::addWGSR(cleaned_data$BMI, sex = 'sex_z', firstPart = 'weight_bestavail', secondPart = 'height_bestavail', thirdPart = 'agedays_bestavail', index ='bfa', output = 'bmiz_bestavail', digits = 3)

# Change out of range BMIZ values to NA 
cleaned_data$BMI <- cleaned_data$BMI |> 
  mutate(bmiz_pub = na_if(bmiz_pub, gt(10)|lt(-10))) |> 
  mutate(bmiz_clinic = na_if(bmiz_clinic, gt(10)|lt(-10))) |> 
  mutate(bmiz_bestavail  = na_if(bmiz_bestavail, gt(10)|lt(-10)))

```

# 4. Long Dataset

```{r}
cleaned_data$Binge <- cleaned_data$Binge |> 
  pivot_longer(cols = matches("\\."),
               names_sep = "\\.",
               names_to = c(".value", "assess_agemos")) 

cleaned_data$Compensatory_Behaviors <- cleaned_data$Compensatory_Behaviors |> 
  pivot_longer(cols = matches("\\."),
               names_sep = "\\.",
               names_to = c(".value", "assess_agemos")) 

cleaned_data$Driven_Exercise <- cleaned_data$Driven_Exercise |> 
  pivot_longer(cols = matches("\\."),
               names_sep = "\\.",
               names_to = c(".value", "assess_agemos")) 

cleaned_data$ED_cognitions <- cleaned_data$ED_cognitions |> 
  pivot_longer(cols = matches("\\."),
               names_sep = "\\.",
               names_to = c(".value", "assess_agemos")) 

long_data <- cleaned_data[[1]]

j = 2
while (j <= length(cleaned_data)) {
  long_data <- full_join(long_data, cleaned_data[[j]])
  j = j+1
}
```

# 5. Wide Dataset

```{r}
cols <- colnames(long_data)
cols <- cols[-c(1:3,65:75 )]

wide_data <- long_data |> 
  tidyr::pivot_wider(id_cols = id,
              values_from = cols,
              names_from = assess_agemos) |> 
  janitor::remove_empty("cols")
```


# 6. Save cleaned data 
```{r}
# Dataset with dataframes separated by measure
ALSPAC_cleaned <- cleaned_data
save(ALSPAC_cleaned, file = 'data/ALSPAC_cleaned.RData') 


# Long Dataframe
ALSPAC_long <- long_data
save(ALSPAC_long, file = 'data/ALSPAC_long.RData') 

# Wide Dataframe
ALSPAC_wide <- wide_data
save(ALSPAC_wide, file = 'data/ALSPAC_wide.RData') 
```

# 7. Clear environment and load data for checking
```{r}
rm(list = ls())
load('data/ALSPAC_cleaned.RData')
load('data/ALSPAC_long.RData')
load('data/ALSPAC_wide.RData')

```

